//go:build legacy_generated_register_stubs

// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:               "fennel",
		Extensions:         []string{".fnl"},
		Language:           FennelLanguage,
		HighlightQuery:     fennelHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("fennel"),
	})
}

const fennelHighlightQuery = "(symbol) @variable\n(number) @number\n"
