//go:build legacy_generated_register_stubs

// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:               "v",
		Extensions:         []string{".v", ".vsh"},
		Language:           VLanguage,
		HighlightQuery:     vHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("v"),
	})
}

const vHighlightQuery = "(function_declaration (identifier) @function)\n"
