//go:build legacy_generated_register_stubs

// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:               "verilog",
		Extensions:         []string{".v", ".sv", ".svh"},
		Language:           VerilogLanguage,
		HighlightQuery:     verilogHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("verilog"),
	})
}

const verilogHighlightQuery = "(module_keyword) @keyword\n(simple_identifier) @type\n"
